version: '3.8'

services:
  # Pocketbase Backend
  pocketbase:
    image: ghcr.io/muchobien/pocketbase:latest
    container_name: nakit-pocketbase
    restart: unless-stopped
    ports:
      - "8090:8090"
    volumes:
      - ./backend/pb_data:/pb_data
      - ./backend/pb_hooks:/pb_hooks:ro
    environment:
      - PB_ENCRYPTION_KEY=${PB_ENCRYPTION_KEY:-your-secret-key}
    command: serve --http=0.0.0.0:8090
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8090/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Next.js Frontend
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: nakit-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_POCKETBASE_URL=http://pocketbase:8090
    depends_on:
      pocketbase:
        condition: service_healthy

volumes:
  pb_data:

